# Teorie:
# 


print("\n================ 3. FUNCTII CU CLOSURE ================\n")

print("NIVEL USOR")
print("----------------------")
print("1. Closure care afiseaza o valoare fixa.")
print("----------------------")
print("2. Closure care pastreaza un numar.")
print("----------------------")
print("3. Closure care aduna o valoare fixa.")
print("----------------------")
print("4. Closure care memoreaza mesaj.")
print("----------------------")
print("5. Closure care foloseste nonlocal.")
print("----------------------")
print("6. Closure care numara apelurile.")
print("----------------------")
print("7. Closure care modifica variabila interna.")
print("----------------------")
print("8. Closure care returneaza produs.")
print("----------------------")
print("9. Closure care foloseste string.")
print("----------------------")
print("10. Closure care afiseaza stare.")

print("\nNIVEL MEDIU")
print("----------------------")
print("1. Closure care implementeaza contor.")
print("----------------------")
print("2. Closure care calculeaza suma cumulativa.")
print("----------------------")
print("3. Closure care valideaza input.")
print("----------------------")
print("4. Closure care pastreaza stare logica.")
print("----------------------")
print("5. Closure care filtreaza valori.")
print("----------------------")
print("6. Closure care simuleaza portofel.")
print("----------------------")
print("7. Closure care tine evidenta apelurilor.")
print("----------------------")
print("8. Closure care implementeaza cache simplu.")
print("----------------------")
print("9. Closure care foloseste if si for.")
print("----------------------")
print("10. Closure care combina date.")

print("\nNIVEL GREU")
print("----------------------")
print("1. Closure care implementeaza mini-cache.")
print("----------------------")
print("2. Closure care simuleaza cont bancar.")
print("----------------------")
print("3. Closure care tine istoric.")
print("----------------------")
print("4. Closure care functioneaza ca rate limiter.")
print("----------------------")
print("5. Closure care gestioneaza stare complexa.")
print("----------------------")
print("6. Closure care filtreaza incremental.")
print("----------------------")
print("7. Closure care gestioneaza sesiuni.")
print("----------------------")
print("8. Closure care combina mai multe functii.")
print("----------------------")
print("9. Closure care memoreaza configuratie.")
print("----------------------")
print("10. Closure care simuleaza sistem.")