# Teorie:
# 


print("\n================ 5. DECORATORI (CUSTOM SI BUILT-IN) ================\n")

print("NIVEL USOR")
print("----------------------")
print("1. Decorator care afiseaza mesaj inainte si dupa.")
print("----------------------")
print("2. Decorator care dubleaza rezultatul.")
print("----------------------")
print("3. Decorator care afiseaza numele functiei.")
print("----------------------")
print("4. Decorator care numara apelurile.")
print("----------------------")
print("5. Decorator care valideaza un argument.")
print("----------------------")
print("6. Decorator care foloseste *args.")
print("----------------------")
print("7. Decorator care foloseste closure.")
print("----------------------")
print("8. Decorator care modifica output.")
print("----------------------")
print("9. Decorator care conditioneaza executia.")
print("----------------------")
print("10. Decorator simplu fara parametri.")

print("\nNIVEL MEDIU")
print("----------------------")
print("1. Decorator care masoara timpul de executie.")
print("----------------------")
print("2. Decorator care valideaza tipuri.")
print("----------------------")
print("3. Decorator care gestioneaza exceptii.")
print("----------------------")
print("4. Decorator care foloseste nonlocal.")
print("----------------------")
print("5. Decorator care primeste parametri.")
print("----------------------")
print("6. Decorator care combina doua decoratoare.")
print("----------------------")
print("7. Decorator care implementeaza cache.")
print("----------------------")
print("8. Decorator care verifica conditii.")
print("----------------------")
print("9. Decorator care controleaza acces.")
print("----------------------")
print("10. Decorator care logheaza input/output.")

print("\nNIVEL GREU")
print("----------------------")
print("1. Decorator cu parametri multipli.")
print("----------------------")
print("2. Decorator care implementeaza rate limiting.")
print("----------------------")
print("3. Decorator care foloseste lru_cache.")
print("----------------------")
print("4. Decorator care foloseste wraps.")
print("----------------------")
print("5. Decorator care modifica semnatura.")
print("----------------------")
print("6. Decorator care compune decoratori.")
print("----------------------")
print("7. Decorator pentru retry logic.")
print("----------------------")
print("8. Decorator pentru autentificare.")
print("----------------------")
print("9. Decorator generic pentru orice functie.")
print("----------------------")
print("10. Decorator care imita context manager.")