# Teorie:
# 


print("\n================ 2. FUNCTII IN FUNCTII (NESTED FUNCTIONS) ================\n")

print("NIVEL USOR")
print("----------------------")
print("1. Functie externa care apeleaza o functie interna.")
print("----------------------")
print("2. Functie externa care afiseaza mesaj din functie interna.")
print("----------------------")
print("3. Functie externa care defineste functie interna simpla.")
print("----------------------")
print("4. Functie externa care returneaza functia interna.")
print("----------------------")
print("5. Functie externa cu functie interna de calcul.")
print("----------------------")
print("6. Functie externa cu doua functii interne.")
print("----------------------")
print("7. Functie externa care controleaza apelul intern.")
print("----------------------")
print("8. Functie externa care foloseste variabila locala.")
print("----------------------")
print("9. Functie externa care afiseaza rezultatul intern.")
print("----------------------")
print("10. Functie externa care returneaza mesaj.")

print("\nNIVEL MEDIU")
print("----------------------")
print("1. Functie externa care returneaza functie interna cu parametru.")
print("----------------------")
print("2. Functie externa care alege functia interna folosind if.")
print("----------------------")
print("3. Functie externa cu functie interna ce proceseaza lista.")
print("----------------------")
print("4. Functie externa care defineste functie interna cu for.")
print("----------------------")
print("5. Functie externa cu functie interna ce foloseste dictionar.")
print("----------------------")
print("6. Functie externa care primeste parametri externi.")
print("----------------------")
print("7. Functie externa cu doua niveluri de functii interne.")
print("----------------------")
print("8. Functie externa care simuleaza meniu.")
print("----------------------")
print("9. Functie externa care intoarce functie de calcul.")
print("----------------------")
print("10. Functie externa cu functie interna reutilizabila.")

print("\nNIVEL GREU")
print("----------------------")
print("1. Functie externa care construieste functii dinamic.")
print("----------------------")
print("2. Functie externa care implementeaza strategie.")
print("----------------------")
print("3. Functie externa care creeaza functie de filtrare.")
print("----------------------")
print("4. Functie externa care incapsuleaza logica complexa.")
print("----------------------")
print("5. Functie externa care controleaza flux complet.")
print("----------------------")
print("6. Functie externa cu validari multiple.")
print("----------------------")
print("7. Functie externa cu functie interna recursiva.")
print("----------------------")
print("8. Functie externa care returneaza functie conditionata.")
print("----------------------")
print("9. Functie externa care gestioneaza stare.")
print("----------------------")
print("10. Functie externa care compune functii.")


