# Teorie:
# 


print("\n================ 4. WRAPPER (APEL EXPLICIT) ================\n")

print("NIVEL USOR")
print("----------------------")
print("1. Wrapper care afiseaza mesaj inainte de apel.")
print("----------------------")
print("2. Wrapper care afiseaza mesaj dupa apel.")
print("----------------------")
print("3. Wrapper care afiseaza argumentele.")
print("----------------------")
print("4. Wrapper care dubleaza rezultatul.")
print("----------------------")
print("5. Wrapper care valideaza un argument.")
print("----------------------")
print("6. Wrapper care afiseaza numele functiei.")
print("----------------------")
print("7. Wrapper care numara apelurile.")
print("----------------------")
print("8. Wrapper care foloseste *args.")
print("----------------------")
print("9. Wrapper care modifica output-ul.")
print("----------------------")
print("10. Wrapper care opreste executia conditionat.")

print("\nNIVEL MEDIU")
print("----------------------")
print("1. Wrapper care masoara timpul de executie.")
print("----------------------")
print("2. Wrapper care valideaza tipurile.")
print("----------------------")
print("3. Wrapper care filtreaza argumente.")
print("----------------------")
print("4. Wrapper care aplica logica conditionata.")
print("----------------------")
print("5. Wrapper care transforma output.")
print("----------------------")
print("6. Wrapper care gestioneaza exceptii.")
print("----------------------")
print("7. Wrapper care foloseste closure.")
print("----------------------")
print("8. Wrapper care aplica mai multe operatii.")
print("----------------------")
print("9. Wrapper care lucreaza cu dictionare.")
print("----------------------")
print("10. Wrapper care simuleaza pipeline.")

print("\nNIVEL GREU")
print("----------------------")
print("1. Wrapper generic pentru orice functie.")
print("----------------------")
print("2. Wrapper care combina mai multe functii.")
print("----------------------")
print("3. Wrapper care implementeaza retry.")
print("----------------------")
print("4. Wrapper care gestioneaza erori.")
print("----------------------")
print("5. Wrapper care controleaza flux complex.")
print("----------------------")
print("6. Wrapper care conditioneaza executia.")
print("----------------------")
print("7. Wrapper care aplica reguli dinamice.")
print("----------------------")
print("8. Wrapper care gestioneaza stare.")
print("----------------------")
print("9. Wrapper care imita decorator.")
print("----------------------")
print("10. Wrapper care extinde comportament.")