#Teorie
# 

print("\n================ DICTIONARE ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Creeaza un dictionar cu 3 chei si valori.")
print("----------------------")
print("2. Acceseaza o valoare dupa cheie (folosind get).")
print("----------------------")
print("3. Adauga o cheie noua si actualizeaza o valoare existenta.")
print("----------------------")
print("4. Sterge o cheie.")
print("----------------------")
print("5. Itereaza chei, valori si perechi cheie-valoare.")
print("----------------------")
print("6. Verifica existenta unei chei.")
print("----------------------")
print("7. Goleste dictionarul.")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Numara aparitiile fiecarui cuvant intr-un text.")
print("----------------------")
print("2. Construieste frecventa literelor dintr-un string.")
print("----------------------")
print("3. Inverseaza un dictionar cu valori unice.")
print("----------------------")
print("4. Combina doua dictionare cu prioritate pentru al doilea.")
print("----------------------")
print("5. Sorteaza cheile dupa valoare.")
print("----------------------")
print("6. Creeaza dict din doua liste cu lungimi diferite.")
print("----------------------")
print("7. Filtreaza cheile care incep cu o litera data.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Group by prima litera.")
print("----------------------")
print("2. Total pe moneda din lista de facturi.")
print("----------------------")
print("3. Normalizeaza cheile unui dictionar.")
print("----------------------")
print("4. Construieste index id -> obiect.")
print("----------------------")
print("5. Top 3 cuvinte frecvente.")
print("----------------------")
print("6. Statistici complete pentru lista de numere.")