#Teorie
# 

print("\n================ FUNCTII ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Functie care returneaza suma a doua numere.")
print("----------------------")
print("2. Functie care returneaza lungimea unui string.")
print("----------------------")
print("3. Functie care afiseaza un mesaj.")
print("----------------------")
print("4. Functie cu parametru implicit.")
print("----------------------")
print("5. Functie care returneaza True/False.")
print("----------------------")
print("6. Functie care returneaza maximul din lista.")
print("----------------------")
print("7. Functie care concateneaza string-uri.")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Functie care valideaza email simplu.")
print("----------------------")
print("2. Functie care returneaza min/max/suma.")
print("----------------------")
print("3. Functie factorial iterativ.")
print("----------------------")
print("4. Functie cu *args.")
print("----------------------")
print("5. Functie cu **kwargs.")
print("----------------------")
print("6. Functie cu validare folosind nested.")
print("----------------------")
print("7. Functie care masoara timpul de executie.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Decorator simplu.")
print("----------------------")
print("2. Closure multiply_by(n).")
print("----------------------")
print("3. Map manual cu functie primita.")
print("----------------------")
print("4. Functie retry.")
print("----------------------")
print("5. Parse JSON cu try/except.")
print("----------------------")
print("6. Curata payload recursiv.")