#Teorie
# 

print("\n================ IF / FOR / WHILE (CONTROL FLOW) ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Citeste un numar si afiseaza daca este pozitiv, negativ sau 0.")
print("----------------------")
print("2. Citeste varsta si afiseaza 'minor' sau 'adult'.")
print("----------------------")
print("3. Afiseaza numerele de la 1 la 20 folosind for.")
print("----------------------")
print("4. Afiseaza numerele pare de la 0 la 50.")
print("----------------------")
print("5. Citeste un N si afiseaza suma numerelor 1..N.")
print("----------------------")
print("6. Folosind while, citeste numere pana cand utilizatorul introduce 0; apoi afiseaza cate ai citit.")
print("----------------------")
print("7. Afiseaza tabla inmultirii pentru un numar dat (1..10).")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Citeste un sir de numere si afiseaza cate sunt pare si cate impare.")
print("----------------------")
print("2. Gaseste maximul dintr-o lista folosind o bucla.")
print("----------------------")
print("3. Afiseaza primele N elemente dintr-o lista folosind for si break.")
print("----------------------")
print("4. Cauta un element intr-o lista si afiseaza indexul sau -1.")
print("----------------------")
print("5. Scrie un meniu simplu in bucla (1-aduna, 2-scade, 0-iesire).")
print("----------------------")
print("6. Afiseaza toti divizorii unui numar.")
print("----------------------")
print("7. Genereaza secventa Fibonacci pana la N termeni.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Parcurge o lista de string-uri si construieste o lista cu cele care contin '@'.")
print("----------------------")
print("2. Primeste o lista de numere si construieste doua liste: pozitive si negative.")
print("----------------------")
print("3. Simuleaza un sistem de autentificare: 3 incercari parola.")
print("----------------------")
print("4. Citeste linii de text pana la 'STOP' si calculeaza totalul de caractere.")
print("----------------------")
print("5. Parcurge un dict de produse si calculeaza totalul pentru un cos.")
print("----------------------")
print("6. Scrie un parser simplu: extrage toate numerele dintr-un text.")