#Teorie
# 

print("\n================ LISTE ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Creeaza o lista cu 5 numere.")
print("----------------------")
print("2. Acceseaza primul si ultimul element.")
print("----------------------")
print("3. Adauga un element (append) si un element la inceput (insert).")
print("----------------------")
print("4. Sterge un element dupa valoare (remove) si dupa index (pop).")
print("----------------------")
print("5. Sorteaza lista crescator si descrescator.")
print("----------------------")
print("6. Inverseaza lista (in place si cu slicing).")
print("----------------------")
print("7. Calculeaza suma elementelor (cu bucla).")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Elimina duplicatele pastrand ordinea.")
print("----------------------")
print("2. Creeaza o lista doar cu numere pare dintr-o lista data.")
print("----------------------")
print("3. Creeaza o lista cu lungimile string-urilor dintr-o lista de cuvinte.")
print("----------------------")
print("4. Gaseste al doilea cel mai mare numar (fara sort).")
print("----------------------")
print("5. Imparte lista in doua liste cat mai egale.")
print("----------------------")
print("6. Combina doua liste fara duplicate pastrand ordinea primei aparitii.")
print("----------------------")
print("7. Roteaza lista cu n pozitii.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Filtreaza produse cu pret > X dintr-o lista de dictionare.")
print("----------------------")
print("2. Construieste perechi (n, n^2) dintr-o lista.")
print("----------------------")
print("3. Grupeaza elementele unei liste in subliste de cate k.")
print("----------------------")
print("4. Interclaseaza doua liste.")
print("----------------------")
print("5. Scrie un diff simplu intre doua liste.")
print("----------------------")
print("6. Simuleaza un stack cu push/pop.")