#Teorie
# 

print("\n================ MODULE SI IMPORT ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Import math si calculeaza sqrt.")
print("----------------------")
print("2. Genereaza numar random.")
print("----------------------")
print("3. Afiseaza data curenta.")
print("----------------------")
print("4. Afiseaza directorul curent.")
print("----------------------")
print("5. Afiseaza versiunea Python.")
print("----------------------")
print("6. Dict in JSON.")
print("----------------------")
print("7. Construieste cale cu pathlib.")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Creeaza si importa utils.py.")
print("----------------------")
print("2. Import cu alias.")
print("----------------------")
print("3. Organizeaza pachet Python.")
print("----------------------")
print("4. Argumente linie comanda (argparse).")
print("----------------------")
print("5. Logging basic.")
print("----------------------")
print("6. Citeste CSV.")
print("----------------------")
print("7. Parse URL.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Mini-proiect modular.")
print("----------------------")
print("2. Proceseaza JSON produse.")
print("----------------------")
print("3. Listeaza fisiere .txt.")
print("----------------------")
print("4. HTTP GET si status code.")
print("----------------------")
print("5. Dataclasses Product.")
print("----------------------")
print("6. Modul config.")