#Teorie
# 

print("\n================ NUMERE (INT / FLOAT) SI OPERATII DE BAZA ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Citeste doua numere si afiseaza suma, diferenta, produsul si catul (cu verificare la impartire la 0).")
print("----------------------")
print("2. Scrie o functie care verifica daca un numar este par.")
print("----------------------")
print("3. Scrie o functie care verifica daca un numar este multiplu de 3 si 5.")
print("----------------------")
print("4. Calculeaza aria si perimetrul unui dreptunghi (date: L, l).")
print("----------------------")
print("5. Converteste grade Celsius in Fahrenheit.")
print("----------------------")
print("6. Calculeaza restul impartirii a doua numere (modulo).")
print("----------------------")
print("7. Rotunjeste un numar float la 2 zecimale (fara a folosi formatari avansate).")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Scrie o functie care primeste un numar si returneaza suma cifrelor.")
print("----------------------")
print("2. Scrie o functie care inverseaza cifrele unui numar (ex: 120 -> 21).")
print("----------------------")
print("3. Verifica daca un numar este prim.")
print("----------------------")
print("4. Scrie o functie care calculeaza cmmdc (GCD) folosind algoritmul lui Euclid.")
print("----------------------")
print("5. Calculeaza puterea (a^b) fara operatorul ** (foloseste bucla).")
print("----------------------")
print("6. Scrie o functie care transforma un numar in baza 2 (string binar) fara bin().")
print("----------------------")
print("7. Calculeaza suma primelor N numere naturale (1..N) in doua moduri: formula si bucla.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Primeste o lista de numere si returneaza un dict cu: min, max, suma, medie, count_pare.")
print("----------------------")
print("2. Primeste un text cu numere separate prin spatii si calculeaza media lor.")
print("----------------------")
print("3. Scrie o functie care valideaza un CNP simplificat (doar lungime 13 si doar cifre).")
print("----------------------")
print("4. Simuleaza un mini-calc: citeste 'a op b' si executa operatia.")
print("----------------------")
print("5. Genereaza o lista cu primele N numere prime.")
print("----------------------")
print("6. Calculeaza suma numerelor dintr-o lista ignorand elementele care nu sunt int.")