#Teorie
# 

print("\n================ OOP (PROGRAMARE ORIENTATA PE OBIECT) ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Clasa goala.")
print("----------------------")
print("2. __init__ cu atribute.")
print("----------------------")
print("3. Metoda care afiseaza mesaj.")
print("----------------------")
print("4. Modifica atribut.")
print("----------------------")
print("5. Obiecte cu stari diferite.")
print("----------------------")
print("6. Metoda care returneaza valoare.")
print("----------------------")
print("7. __str__ implementat.")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. BankAccount.")
print("----------------------")
print("2. Product cu TVA.")
print("----------------------")
print("3. Mostenire Employee / Manager.")
print("----------------------")
print("4. @property pentru validare.")
print("----------------------")
print("5. Clasa cu lista interna.")
print("----------------------")
print("6. classmethod din dict.")
print("----------------------")
print("7. staticmethod de validare.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Model User / Invoice / LineItem.")
print("----------------------")
print("2. Obiecte din JSON.")
print("----------------------")
print("3. Comparare obiecte.")
print("----------------------")
print("4. Repository in memorie.")
print("----------------------")
print("5. Sistem de permisiuni.")
print("----------------------")
print("6. Mini-simulator comenzi.")