#Teorie
# 

print("\n================ STRING-URI SI SLICING ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. Extrage primele 3 caractere dintr-un string.")
print("----------------------")
print("2. Extrage ultimele 2 caractere dintr-un string.")
print("----------------------")
print("3. Inverseaza un string folosind slicing.")
print("----------------------")
print("4. Extrage fiecare al doilea caracter.")
print("----------------------")
print("5. Verifica daca un string contine un substring.")
print("----------------------")
print("6. Inlocuieste toate spatiile cu underscore.")
print("----------------------")
print("7. Afiseaza lungimea string-ului.")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Elimina spatiile de la inceput si final fara strip().")
print("----------------------")
print("2. Mascheaza un email.")
print("----------------------")
print("3. Extrage domeniul dintr-un email.")
print("----------------------")
print("4. Verifica daca un string este palindrom.")
print("----------------------")
print("5. Numara vocalele dintr-un string.")
print("----------------------")
print("6. Elimina toate cifrele dintr-un string.")
print("----------------------")
print("7. Gaseste prima si ultima aparitie a unui caracter.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Normalizeaza un nume complet.")
print("----------------------")
print("2. Valideaza un username.")
print("----------------------")
print("3. Extrage cuvintele care incep cu litera mare.")
print("----------------------")
print("4. Implementeaza slugify simplu.")
print("----------------------")
print("5. Implementeaza Caesar cipher.")
print("----------------------")
print("6. Comprima spatiile dintr-un text.")