#Teorie
# 

print("\n================ EXCEPTII SI VALIDARE ================\n")

print("NIVEL 1 – BAZA")
print("----------------------")
print("1. ZeroDivisionError.")
print("----------------------")
print("2. ValueError la int.")
print("----------------------")
print("3. FileNotFoundError.")
print("----------------------")
print("4. finally.")
print("----------------------")
print("5. else la try/except.")
print("----------------------")
print("6. Return None la input invalid.")
print("----------------------")
print("7. KeyError.")

print("\nNIVEL 2 – GANDIRE")
print("----------------------")
print("1. Valideaza emailuri.")
print("----------------------")
print("2. safe_int.")
print("----------------------")
print("3. Parse data.")
print("----------------------")
print("4. raise ValueError.")
print("----------------------")
print("5. Exceptie custom.")
print("----------------------")
print("6. JSONDecodeError.")
print("----------------------")
print("7. Validare payload.")

print("\nNIVEL 3 – COMBINARE")
print("----------------------")
print("1. Wrapper cu logging.")
print("----------------------")
print("2. CSV cu linii corupte.")
print("----------------------")
print("3. Mini ETL.")
print("----------------------")
print("4. Validare in lant.")
print("----------------------")
print("5. Fallback surse date.")
print("----------------------")
print("6. Retry cu backoff.")